# GCP Cloud Run deployment configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
  name: strava-coverage
spec:
  template:
    metadata:
      annotations:
        # Allow up to 1000 concurrent requests per instance
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/strava-coverage:latest
        ports:
        - containerPort: 8080
        env:
        - name: STRAVA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: strava-secrets
              key: client_id
        - name: STRAVA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: strava-secrets
              key: client_secret
        - name: STRAVA_REDIRECT_URI
          value: "https://YOUR_DOMAIN.run.app/oauth/callback"
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: connection_string
        - name: GIN_MODE
          value: "release"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health  
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
  traffic:
  - percent: 100
    latestRevision: true